#+TITLE: Quotes by Donald Trump

* Topic

** Forgein Politics
*** Russia
- "I believe an easing of tensions, and improved relations with Russia—from a position of strength only—is possible, absolutely possible. Some say the Russians won’t be reasonable. I intend to find out." [fn:wsj]
*** China
- "China’s entrance into the World Trade Organization has enabled the greatest jobs theft in history." [fn:wsj]
*** Mexico
- "When Mexico sends its people, they’re not sending their best...They’re sending people that have lots of problems, and they’re bringing those problems with us. They’re bringing drugs. They’re bringing crime. They’re rapists." [fn:wsj]
- “I will build a great wall – and nobody builds walls better than me, believe me – and I’ll build them very inexpensively. I will build a great, great wall on our southern border, and I will make Mexico pay for that wall. Mark my words.”  [fn:1]
*** Iraq
- "George Bush made a mistake. We can make mistakes. But that one was a beauty. We should have never been in Iraq. We have destabilized the Middle East." [fn:wsj]
*** Iran
- "Iran is a very big problem and will continue to be. But if I’m elected president, I know how to deal with trouble." [fn:wsj]
*** Israel
- "When I become president, the days of treating Israel like a second-class citizen will end on day one." [fn:wsj]

** NATO
- "If we cannot be properly reimbursed for the tremendous cost of our military protecting other countries….then yes, I would be absolutely prepared to tell those countries, ‘Congratulations, you will be defending yourself.’" [fn:wsj]

** Nuclear Weapons
- "Somebody hits us within ISIS — you wouldn`t fight back with a nuke?" [fn:tp]

** Women
- “Robert Pattinson should not take back Kristen Stewart. She cheated on him like a dog & will do it again – just watch. He can do much better!” [fn:1]
- “Ariana Huffington is unattractive, both inside and out. I fully understand why her former husband left her for a man – he made a good decision.” [fn:1]
- “You know, it really doesn’t matter what the media write as long as you’ve got a young, and beautiful, piece of ass.”  [fn:1]
- “If I were running ‘The View’, I’d fire Rosie O’Donnell. I mean, I’d look at her right in that fat, ugly face of hers, I’d say ‘Rosie, you’re fired.’” [fn:1]
- “All of the women on The Apprentice flirted with me – consciously or unconsciously. That’s to be expected.” [fn:1]
- “I’ve said if Ivanka weren’t my daughter, perhaps I’d be dating her.” [fn:1]

** Birther Conspiracy
- “An ‘extremely credible source’ has called my office and told me that Barack Obama’s birth certificate is a fraud” [fn:1]

** Public Safety
- “Our great African-American President hasn’t exactly had a positive impact on the thugs who are so happily and openly destroying Baltimore.” [fn:1]

** Bragging
- “The beauty of me is that I’m very rich.” [fn:1]
- “I think the only difference between me and the other candidates is that I’m more honest and my women are more beautiful.” [fn:1]
- “The point is, you can never be too greedy.” [fn:1]
- “My Twitter has become so powerful that I can actually make my enemies tell the truth.” [fn:1]
- “My IQ is one of the highest — and you all know it! Please don’t feel so stupid or insecure; it’s not your fault.” [fn:1]

** Global Warming
- “It’s freezing and snowing in New York – we need global warming!” [fn:1]

* Sources
- [fn:1] http://www.marieclaire.co.uk/entertainment/people/donald-trump-quotes-57213
- [fn:wsj] http://graphics.wsj.com/elections/2016/donald-trump-hillary-clinton-on-foreign-policy/
- [fn:tp] https://thinkprogress.org/9-terrifying-things-donald-trump-has-publicly-said-about-nuclear-weapons-99f6290bc32a#.v1mt68sjw
